---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt
name: cephfs

releases:
  - name: cephfs
    version: latest

update:
  canaries: 1
  canary_watch_time: 15000-60000
  update_watch_time: 15000-60000
  max_in_flight: 2

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

credentials:
  username: fucker
  password: ass

jobs:
  - name: cephfs
    instances: 5
    vm_type: default  
    persistent_disk: 5000
    stemcell: default
    networks:
    - name: default
    jobs:
    - release: cephfs
      name: cephfs
    consumes: 
      ceph-storage:{from: ceph-storage}
    provides:
      ceph-storage:{as: ceph-storage} 
    update:
      serial: true
    properties:
      cephfs:
        client_keyring: |
          [client.admin]
            key = AQDrWzJae1DGCxAAXGvPgKptRBAIGM3bxztrtw==
            caps mds = "allow"
            caps mon = "allow *"
            caps osd = "allow *"