---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt
name: cephfs

releases:
  - name: cephfs
    version: latest

update:
  canaries: 1
  canary_watch_time: 15000-30000
  update_watch_time: 15000-30000
  max_in_flight: 2

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

credentials:
  username: fucker
  password: ass

jobs:
  - name: cephfs
    instances: 1
    vm_type: default  
    persistent_disk_type: default
    stemcell: default
    networks:
    - name: default
    jobs:
    - release: cephfs
      name: cephfs
    update:
      serial: true
    properties:
      cephfs:
        client_keyring: |
          